"teams/redTeam.res"
{
	"teamNameLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"teamNameLabel"
		"xpos"			"20"
		"ypos"			"10"
		"zpos"		"2"
		"wide"			"530"
		"tall"			"140"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Slayers"
//		"labelText"		"#SDK_Team_Red"
		"textAlignment"		"North-west"
		"dulltext"		"0"
		"brighttext"		"1"
		"font"			"MenuTitle"
		"fillcolor"		"Blank"
		"wrap"			"0"
	}
	"TeamImage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"TeamImage"
		"xpos"		"0"
		"ypos"		"0"
		"zpos"		"1"
		"wide"		"530"
		"tall"		"140"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1" 
		"tabPosition"		"0"
		"fillcolor"		"Blue"
		"labelText"		""
		"image"			"SlayBanner"
		"scaleImage"	"1"
	}
	"teamInfo"
	{
		"ControlName"		"RichText"
		"fieldName"		"teamInfo"
		"xpos"		"0"
		"ypos"		"140"
		"wide"		"530"
		"tall"		"280"
		"autoResize"		"3"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"maxchars"		"-1"
		"text"			"#teaminfo_red"
		"wrap"			"1"
		"textAlignment"		"north-west"
		"font"			"ClassMenuDefaultSmall"
	}
}